ignore:
  - id: "GO-2025-4007"
    reason: "This doesn't affect our application"
  - id: "GO-2025-4008"
    reason: "This doesn't affect our application"
  - id: "GO-2025-4009"
    reason: "This doesn't affect our application"
  - id: "GO-2025-4010"
    reason: "This doesn't affect our application"
  - id: "GO-2025-4011"
    reason: "This doesn't affect our application"
  - id: "GO-2025-4012"
    reason: "This doesn't affect our application"
  - id: "GO-2025-4013"
    reason: "This doesn't affect our application"